version compose & version rewrite on walk

diff --git a/bin/build-lib b/bin/build-lib
--- a/bin/build-lib
+++ b/bin/build-lib
@@ -67,6 +67,7 @@ breqWhichVersion() {
   shift
   local avail=($@)
 
+  # fixme: temp test entry
   testAddToVersionSamples $cond $avail # generate version samples
 
   for ((idx=0; idx < ${#avail[@]}; ++idx)); do
@@ -210,6 +211,7 @@ breqAddNode() {
       cyclic_dir="$req_dir"
       if [[ $prev_idx -ge 0 ]]; then # store cyclic parent
         cyclic_parent=${pa[$prev_idx]}
+        # cyclic_parent="$p" # fixme: check for correct parent name
       else #! cyclic source is task themself - giving up
         breqPrintStatus $level "err" "unbreakable circle"
         echo "$bspec"  # pass current package upstack
@@ -231,15 +233,31 @@ breqAddNode() {
 
   #? ---- cyclic depend ----
   if [[ -n $is_cyclic ]]; then # yep, cyclic dependecy
-    local cycled_bspec="$bname/`cat $cyclic_dir/.version | tr -d ' '`"
+    local cycled_bver=$(cat $cyclic_dir/.version | tr -d ' ')
+    local cycled_bspec="$bname/${cycled_bver// /}"
     # mark nodes
-    echo "$parent $bspec" > "$cyclic_dir/.cyclic"
+    echo "$bspec" > "$cyclic_dir/.cyclic"
     echo "$cycled_bspec" > "$req_dir/.cyclic"
     breqPrintStatus $level "warn" "cyclic";
-    if [[ "$cycled_bspec" == "$bspec" ]]; then # node of cycle may be with diff version req
+    if [[ "$cycled_bspec" != "$bspec" ]]; then # node of cycle may be with diff version req
       #* package may depend on other version, can we solve?
       # todo: write version compatibily checks, for now only warn
-      breqPrintStatus $level "warn" "version";
+
+      local ver_rw
+      if [[ -n "$cycled_bver" || -n "$bver" ]]; then
+        ver_rw=$(dverCompose "$cycled_bver" "$(bspecVersionHR $bspec)")
+        local ver_code="$?"
+        testAddToVReqSamples "$cycled_bver" "$(bspecVersionHR $bspec)" "$ver_rw" "$ver_code" # fixme: test samples entry
+        if [[ "$ver_code" -gt 0 ]]; then #! cannot compose vreqs - giving up
+          breqPrintStatus $level "err" "version: \"${cycled_bver// /} U ${bver// /}\""' => '"\"${ver_rw// /}\"";
+          echo "$bspec" # pass current package upstack
+          return 1 # cyclic themselfs isn't failure
+        fi
+      else
+        [[ -n "$cycled_bver" ]] && ver_rw="$cycled_bver" || ver_rw="$bver"
+      fi
+
+      breqPrintStatus $level "warn" "version: \"${cycled_bver// /} U ${bver// /}\""' => '"\"${ver_rw// /}\"";
     fi
     echo "$bspec" # pass current package upstack
     return 0 # cyclic themselfs isn't failure
diff --git a/bin/debver-lib b/bin/debver-lib
--- a/bin/debver-lib
+++ b/bin/debver-lib
@@ -7,7 +7,7 @@
 # @description Function to compare two debian's version strings. Compares by left to right by single character.
 #
 # @example
-#    $(dverCmp <left_ver> <right_ver>)"
+#    $(dverCmp <left_ver> <right_ver>)
 #
 # @arg `left` left debian version string.
 # @arg `right` right debian version string.
@@ -114,7 +114,7 @@ dverCmp() {
 # @description Function to extract condition operator from depend requrenment string.
 #
 # @example
-#    $(dverCondition <req>)"
+#    $(dverCondition <req>)
 #
 # @arg `req` requrenment string like ">= 2.4 2.31-13+deb11u6".
 #
@@ -147,7 +147,7 @@ dverTarget() {
 # @description Function to apply depend requrenment string to package version.
 #
 # @example
-#    $(dverMatch <req> <version>)"
+#    $(dverMatch <req> <version>)
 #
 # @arg `req` requrenment string like ">= 2.4 2.31-13+deb11u6".
 # @arg `version` package version.
@@ -175,4 +175,109 @@ dverMatch() {
   esac
 
   echo "$match"
+}
+
+# todo: test cover
+# @description Function to compose two version's requirenment string.
+#   Conposition done in *non-extending* mode (e.g. result of
+#   composition of ">= 2.4" + ">= 2.5" will be ">= 2.5")
+#
+# @example
+#    $(dverCompose <left> <right>)
+#
+# @arg `left` requrenment string to compose with right (e.g. ">= 2.4").
+# @arg `right` requrenment string to compose (e.g. ">= 2.5").
+#
+# @stdout new composed version requirenment string on success.
+# @stdout "" real result of composition is empty (if exitcode = 0).
+#
+# @exitcode 0 on success composition (in this case )
+# @exitcode 1 on failure
+#
+# @see [version requrenment string](https://manpages.ubuntu.com/manpages/xenial/en/man5/deb-control.5.html)
+dverCompose() {
+  local l="$1" r="$2"
+  local lc=$(dverCondition "$l") rc=$(dverCondition "$r")
+  local lt=$(dverTarget "$l") rt=$(dverTarget "$r")
+  local res="false"
+
+  # fixme: implement '><' case
+  if [[ "${lc:0:1}" == '>' && "${rc:0:1}" == '<' ]]; then
+    echo ""
+    return 1
+  fi
+
+  #? [= & >] and [> & =] cases
+  if [[ "$lc" == '=' && "${rc:0:1}" == '>' ]] ||
+     [[ "${lc:0:1}" == '>' && "$rc" == '=' ]]
+  then
+    local cmp
+    # fixme: in dverCmp wrong op order
+    if [[ "${lc:0:1}" == '>' && "$rc" == '=' ]]; then  #? [> & =] variant
+      local tmp="$l"; l="$r"; r="$tmp"
+      lc=$(dverCondition "$l"); rc=$(dverCondition "$r")
+      lt=$(dverTarget "$l"); rt=$(dverTarget "$r")
+    fi
+    cmp=$(dverCmp "$rt" "$lt")
+    case $cmp in
+      '>') echo "= $lt" && return 0;;
+      '=') [[ "${rc:1:1}" == '=' ]] && echo "= $lt" && return 0 || echo "" && return 0 ;;
+      '<') echo "" && return 0 ;;
+        *) echo "" && return 1 ;;
+    esac
+  fi
+
+  #? [= & <] or [< & =] cases
+  if [[ "$lc" == '=' && "${rc:0:1}" == '<' ]] ||
+     [[ "${lc:0:1}" == '<' && "$rc" == '=' ]]
+  then
+    local cmp
+    # fixme: in dverCmp wrong op order
+    if [[ "${lc:0:1}" == '<' && "$rc" == '=' ]]; then  #? [< & =] variant
+      local tmp="$l"; l="$r"; r="$tmp"
+      lc=$(dverCondition "$l"); rc=$(dverCondition "$r")
+      lt=$(dverTarget "$l"); rt=$(dverTarget "$r")
+    fi
+    cmp=$(dverCmp "$rt" "$lt")
+    case $cmp in
+      '<') echo "= $lt" && return 0;;
+      '=') [[ "${rc:1:1}" == '=' ]] && echo "= $lt" || echo "" ; return 0 ;;
+      '<') echo "" && return 0 ;;
+        *) echo "" && return 1 ;;
+    esac
+  fi
+
+  #? = & = case
+  if [[ "$lc" == '=' && "$rc" == '=' ]]; then
+    if [[ $(dverCmp "$rt" "$lt") == '=' ]]; then
+      echo "$r" && return 0
+    else
+      echo "" && return 1
+    fi
+  fi
+
+  #? [> & >] or [< & <] cases
+  if [[ "${lc:0:1}" == '>' && "${rc:0:1}" == '>' ]] ||
+     [[ "${lc:0:1}" == '<' && "${rc:0:1}" == '<' ]]
+  then
+    # fixme: in dverCmp wrong op order
+    local cmp=$(dverCmp "$rt" "$lt")
+    if [[ "${lc:0:1}" == '<' && "${rc:0:1}" == '<' ]]; then  #? [< & <] variant
+      case $cmp in
+      '<') echo "$l" && return 0;;
+      '=') [[ "${lc:1:1}" == '=' ]] || echo "$r"; [[ "${rc:1:1}" == '=' ]] || echo "$l"; return 0;;
+      '>') echo "$r" && return 0 ;;
+        *) echo "" && return 1 ;;
+    esac
+    fi
+    case $cmp in
+      '>') echo "$l" && return 0;;
+      '=') [[ "${lc:1:1}" == '=' ]] || echo "$l"; [[ "${rc:1:1}" == '=' ]] || echo "$r"; return 0;;
+      '<') echo "$r" && return 0 ;;
+        *) echo "" && return 1 ;;
+    esac
+  fi
+
+  echo "$res"
+  return 1
 }
