depends bugfixes

diff --git a/bin/build-lib b/bin/build-lib
--- a/bin/build-lib
+++ b/bin/build-lib
@@ -335,6 +335,26 @@ breqAddNode() {
 
   #* nodeps is ok - check for cyclic we done earlier
   if [[ ${#da[@]} -eq 0 ]]; then
+    # fixme: possible bug
+    if [[ "${bver:0:1}" == '>' || "${bver:0:1}" == '<' || "${bver:0:1}" == '=' ]]; then
+      local new_vstr=$(breqPackString "$(sed -n 's/^Version: \(.*\)$/\1/pg' <<< $str)")
+      unset newver_a; local newver_a
+      for line in ${new_vstr//"\n"/ }; do
+        line=$(tr -cd '[:print:]' <<< "$line")
+        newver_a+=($line)
+      done
+      local new_vr=$(sed 's/\([><=]\+\)\([^ ]\+\)$/\1 \2/' <<< "$bver")
+      for ((vidx=0; vids<${#newver_a[@]}; ++vids)); do
+        [[ -n $(dverMatch "$new_vr" "${newver_a[$vidx]}") ]] && break
+      done
+      if [[ $vidx -ge ${#newver_a[@]} ]]; then
+        breqPrintStatus $level "err" "!ver"
+        echo "$bspec"
+        return 1 #! nover
+      fi
+      bspec="$bname/${newver_a[$vidx]}"
+      bver="${newver_a[$vidx]}"
+    fi
     # fixme: ugly & boilerplate & possible bug
     #? ---- gathering provides ----
     local prov_str=$(breqPackString "$(sed -n 's/^Provides: \(.*\)$/\1/pg' <<< $str)")
@@ -346,13 +366,10 @@ breqAddNode() {
     local provides="${prov_a[$idx]}"
     provides=$(breqParsePacked "${provides[@]}")
     provides=$(sed 's/\/=/\//g' <<< "$provides") # remove = from provides
-    # fixme: possible bug
-    bver=$(sed 's/^[=>< ]\+//g' <<< "$bver") # remove <=> from package
+    #? ---- /provides ----
     echo "$level $bname/$bver $provides" >> "$BREQ_DIR/$task/$BREQ_FLATTEN" # todo: cover with tests
     # fixme: not actualy needed
     echo "$provides" > "$req_dir/.provides" # save depend's provides
-    #? ---- /provides ----
-    # echo "$level $bspec" >> "$BREQ_DIR/$task/$BREQ_FLATTEN"
     breqPrintStatus $level "nodep"
     echo "$retvalue"  # don't mutate retvalue
     return 0
@@ -460,65 +477,65 @@ buildTask() {
 
   # fixme: test mode
   # info "buildTask /$task/" "... taskSumVReq skipped ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_FLATTEN_RW" ]] && rm -f "$BREQ_DIR/$task/$BREQ_FLATTEN_RW"
-  # info $task "versions ..."
-  # taskSumVreq "$task" "$BREQ_FLATTEN" "$BREQ_FLATTEN_RW"
+  [[ -f "$BREQ_DIR/$task/$BREQ_FLATTEN_RW" ]] && rm -f "$BREQ_DIR/$task/$BREQ_FLATTEN_RW"
+  info $task "versions ..."
+  taskSumVreq "$task" "$BREQ_FLATTEN" "$BREQ_FLATTEN_RW"
 
   # fixme: test mode
-  info "buildTask /$task/" "packages (1/4): ... taskFinalDepends skipped ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS"
-  # info $task "packages (1/4): packages list ..."
-  # taskFinalDepends "$task" "$BREQ_FLATTEN_RW" "$BREQ_PKGS"
-  # [[ $? -gt 0 ]] && error 1 FDEPS "finalization of depends failed"
+  # info "buildTask /$task/" "packages (1/4): ... taskFinalDepends skipped ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS"
+  info $task "packages (1/4): packages list ..."
+  taskFinalDepends "$task" "$BREQ_FLATTEN_RW" "$BREQ_PKGS"
+  [[ $? -gt 0 ]] && error 1 FDEPS "finalization of depends failed"
 
   # fixme: test mode
-  info "buildTask /$task/" "packages (2/4): ... taskUnalias skipped ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_UNALIAS" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_UNALIAS"
-  # info $task "packages (2/4): solving virtuals ..."
-  # taskUnalias "$task" "$BREQ_PKGS" "$BREQ_PKGS_UNALIAS"
-  # [[ $? -gt 0 ]] && error 1 FDEPS "solving virtuals failed"
+  # info "buildTask /$task/" "packages (2/4): ... taskUnalias skipped ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_UNALIAS" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_UNALIAS"
+  info $task "packages (2/4): solving virtuals ..."
+  taskUnalias "$task" "$BREQ_PKGS" "$BREQ_PKGS_UNALIAS"
+  [[ $? -gt 0 ]] && error 1 FDEPS "solving virtuals failed"
 
   # todo: is actually needed
   # fixme: test mode
-  info "buildTask /$task/" "packages (3/4): ... taskSumVreq skipped ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_RW" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_RW"
-  # info $task "packages (3/4): making list ..."
-  # taskSumVreq "$task" "$BREQ_PKGS_UNALIAS" "$BREQ_PKGS_RW"
-  # [[ $? -gt 0 ]] && error 1 FDEPS "creation of pkg list failed"
+  # info "buildTask /$task/" "packages (3/4): ... taskSumVreq skipped ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_RW" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_RW"
+  info $task "packages (3/4): making list ..."
+  taskSumVreq "$task" "$BREQ_PKGS_UNALIAS" "$BREQ_PKGS_RW"
+  [[ $? -gt 0 ]] && error 1 FDEPS "creation of pkg list failed"
 
   # fixme: test mode
-  info "buildTask /$task/" "packages (4/4): ... taskClearDepends skipped ..."
-  # info $task "packages (4/4): cleaning list ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_CLR" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_CLR"
-  # taskClearDepends "$task" "$BREQ_PKGS_RW" "$BREQ_PKGS_CLR"
-  # [[ $? -gt 0 ]] && error 1 FDEPS "cleaning of depends failed"
+  # info "buildTask /$task/" "packages (4/4): ... taskClearDepends skipped ..."
+  info $task "packages (4/4): cleaning list ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_CLR" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_CLR"
+  taskClearDepends "$task" "$BREQ_PKGS_RW" "$BREQ_PKGS_CLR"
+  [[ $? -gt 0 ]] && error 1 FDEPS "cleaning of depends failed"
 
   # fixme: test mode
-  info "buildTask /$task/" "install (1/4): ... taskFilterInstalled skipped ..."
-  # info $task "install (1/4): filter installed ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_INST" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_INST"
-  # taskFilterInstalled "$task" "$BREQ_PKGS_CLR" "$BREQ_PKGS_INST"
-  # [[ $? -gt 0 ]] && error 1 DPKG "filtering installed failed"
+  # info "buildTask /$task/" "install (1/4): ... taskFilterInstalled skipped ..."
+  info $task "install (1/4): filter installed ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_INST" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_INST"
+  taskFilterInstalled "$task" "$BREQ_PKGS_CLR" "$BREQ_PKGS_INST"
+  [[ $? -gt 0 ]] && error 1 DPKG "filtering installed failed"
 
   # fixme: test mode
-  info "buildTask /$task/" "install (2/4): ... taskMkInstall skipped ..."
-  # info $task "install (2/4): pkgs list ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_INST_FLT" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_INST_FLT"
-  # taskMkInstall "$task" "$BREQ_PKGS_INST" "$BREQ_PKGS_INST_FLT"
-  # [[ $? -gt 0 ]] && error 1 DPKG "mk install list failed"
+  # info "buildTask /$task/" "install (2/4): ... taskMkInstall skipped ..."
+  info $task "install (2/4): pkgs list ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_INST_FLT" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_INST_FLT"
+  taskMkInstall "$task" "$BREQ_PKGS_INST" "$BREQ_PKGS_INST_FLT"
+  [[ $? -gt 0 ]] && error 1 DPKG "mk install list failed"
 
   # fixme: test mode
   # info "buildTask /$task/" "install (3/4): ... taskDload skipped ..."
-  # info $task "install (3/4): pkgs dload ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_DLSH" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_DLSH"
-  # [[ -d "$(dockerRelativePath sh)/$task" ]] && dockerRmDir "./$(tagValue sh)/$task"
-  # [[ -d "$(dockerRelativePath dbin)/$task" ]] && dockerRmDir ./"$(tagValue dbin)/$task"
-  # taskDload "$task" "$BREQ_PKGS_INST_FLT" "$BREQ_PKGS_DLSH"
-  # [[ $? -gt 0 ]] && error 1 DPKG "dload install list failed"
+  info $task "install (3/4): pkgs dload ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_DLSH" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_DLSH"
+  [[ -d "$(dockerRelativePath sh)/$task" ]] && dockerRmDir "./$(tagValue sh)/$task"
+  [[ -d "$(dockerRelativePath dbin)/$task" ]] && dockerRmDir ./"$(tagValue dbin)/$task"
+  taskDload "$task" "$BREQ_PKGS_INST_FLT" "$BREQ_PKGS_DLSH"
+  [[ $? -gt 0 ]] && error 1 DPKG "dload install list failed"
 
   # fixme: test mode
   # info "buildTask /$task/" "install (4/4): ... taskDebInstall skipped ..."
-  info $task "install (4/4): dpkg install ..."
+  # info $task "install (4/4): dpkg install ..."
   [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_ISH" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_ISH"
   [[ -f "$(dockerRelativePath sh)/$task/$BREQ_PKGS_ISH" ]] && dockerRmDir ./"$(tagValue sh)/$task/$BREQ_PKGS_ISH"
   [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_USH" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_USH"
diff --git a/bin/task-lib b/bin/task-lib
--- a/bin/task-lib
+++ b/bin/task-lib
@@ -65,6 +65,9 @@ taskClearFHS() {
   # fixme: test mode
   # dockerExec rm -rf {"$btree","$srcdir","$bindir","$tmpdir"}
   # [[ -d "$btree" ]] && rm -rf "$btree"
+  # mkdir -p "$btree"
+  # touch "$btree/.flatten"
+  # touch "$btree/.virtuals"
 }
 
 # todo: refactor
@@ -84,7 +87,7 @@ taskInit() {
   fi
 
   # fixme: test mode
-  # info "taskInit /$task/" "... sources skipped ..."
+  info "taskInit /$task/" "... sources skipped ..."
   # taskMakeFHS $task
   # info $task "sources ..."
   # [[ $(dockerAptSources $task) -eq 0 ]] || error 1 $task "apt-get source failed!"
@@ -138,6 +141,7 @@ taskReqs() {
 
   local dsc=$(taskDsc $task)
   local bspecs=($(taskParseBR "$(cat $dsc | sed -n 's/Build-Depends:\(.*\)/\1/p')"))
+  bspecs+=($(taskParseBR "$(cat $dsc | sed -n 's/Build-Depends-Indep:\(.*\)/\1/p')"))
 
   for ((i=0; i<${#bspecs[@]}; ++i)); do
     #? ---- virtual ----
@@ -274,10 +278,15 @@ taskSumVreq() {
 
           # fixme: fix dverCompose arg order
           rw_bver=$(dverCompose "$dst_bver" "$rw_bver")
+          local errc="$?"
 
-          if [[ $? -gt 0 ]] || [[ -z "$rw_bver" ]]; then #! empty vreq is also bad
-            error 1 VERSUM "fails to compose with $dst_bver at line $(( $li + 1 )) '${lines[$li]:0:18}...'"
-            return 1
+          if [[ $errc -gt 0 ]] || [[ -z "$rw_bver" ]]; then #! empty vreq is also bad
+            if [[ $errc -eq 2 ]]; then #! not implemented is not a caller problem
+              warning "$task" "not implemented compose with ${dst_bver:0:12}... with ${rw_bver:0:12}... at line $(( $li + 1 ))"
+            else
+              error 1 VERSUM "fails to compose with $dst_bver at line $(( $li + 1 )) '${lines[$li]:0:18}...'"
+              return 1
+            fi
           fi
         fi
 
