depends finalization - test run

diff --git a/bin/build-lib b/bin/build-lib
--- a/bin/build-lib
+++ b/bin/build-lib
@@ -388,9 +388,9 @@ buildInit() {
 
   # fixme: ugly
   # fixme: test mode
-  # info buildInit "--- test mode ---"
-  guestClearFHS
-  guestCreateFHS
+  info buildInit "--- test mode ---"
+  # guestClearFHS
+  # guestCreateFHS
 }
 
 # build task: buildTask <task>
@@ -399,43 +399,44 @@ buildTask() {
   local bspecs
 
   # fixme: test mode
-  # info "buildTask /$task/" "... taskInit skipped ..."
-  taskInit $task
-  bspecs=$(taskReqs $task)
+  info "buildTask /$task/" "... taskInit skipped ..."
+  # taskInit $task
+  # bspecs=$(taskReqs $task)
 
   # fixme: test mode
-  # info "buildTask /$task/" "... breqAddNode skipped ..."
-  local retcode last_package
-  for bs in ${bspecs[@]}; do
-    last_package=$(breqAddNode 0 "$bs" "" "$task")
-    retcode=$?
-    [[ $retcode -gt 0 ]] && error 1 EDEPEND "failed to get depended package: $(bspecName $last_package)"
-    echo "" # instead [ OK ]
-  done
+  info "buildTask /$task/" "... breqAddNode skipped ..."
+  # local retcode last_package
+  # for bs in ${bspecs[@]}; do
+  #   last_package=$(breqAddNode 0 "$bs" "" "$task")
+  #   retcode=$?
+  #   [[ $retcode -gt 0 ]] && error 1 EDEPEND "failed to get depended package: $(bspecName $last_package)"
+  #   echo "" # instead [ OK ]
+  # done
 
   # fixme: test mode
   # info "buildTask /$task/" "... taskSumVReq skipped ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_FLATTEN_RW" ]] && rm -f "$BREQ_DIR/$task/$BREQ_FLATTEN_RW"
   info $task "versions ..."
   taskSumVreq "$task" "$BREQ_FLATTEN" "$BREQ_FLATTEN_RW"
 
   # fixme: test mode
   # info "buildTask /$task/" "packages (1/4): ... taskFinalDepends skipped ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS"
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS"
   info $task "packages (1/4): packages list ..."
   taskFinalDepends "$task" "$BREQ_FLATTEN_RW" "$BREQ_PKGS"
   [[ $? -gt 0 ]] && error 1 FDEPS "finalization of depends failed"
 
   # fixme: test mode
   # info "buildTask /$task/" "packages (1/4): ... taskUnalias skipped ..."
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_UNALIAS" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_UNALIAS"
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_UNALIAS" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_UNALIAS"
   info $task "packages (2/4): solving virtuals ..."
   taskUnalias "$task" "$BREQ_PKGS" "$BREQ_PKGS_UNALIAS"
-  # taskUnalias "$task" ".packages-sample" ".packages-sample-rw"
   [[ $? -gt 0 ]] && error 1 FDEPS "solving virtuals failed"
 
   # todo: is actually needed
   # fixme: test mode
   # info "buildTask /$task/" "packages (3/4): ... taskSumVreq skipped ..."
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_RW" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_RW"
   info $task "packages (3/4): making list ..."
   taskSumVreq "$task" "$BREQ_PKGS_UNALIAS" "$BREQ_PKGS_RW"
   [[ $? -gt 0 ]] && error 1 FDEPS "cleaning of depends failed"
@@ -443,8 +444,7 @@ buildTask() {
   # fixme: test mode
   # info "buildTask /$task/" "packages (4/4): ... taskClearDepends skipped ..."
   info $task "packages (4/4): cleaning list ..."
-  # cp "$BREQ_DIR/$task/$BREQ_PACKAGES" "$BREQ_DIR/$task/$BREQ_PACKAGES_RW"
-  # [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_CLR" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_CLR"
+  [[ -f "$BREQ_DIR/$task/$BREQ_PKGS_CLR" ]] && rm -f "$BREQ_DIR/$task/$BREQ_PKGS_CLR"
   taskClearDepends "$task" "$BREQ_PKGS_RW" "$BREQ_PKGS_CLR"
   [[ $? -gt 0 ]] && error 1 FDEPS "cleaning of depends failed"
 }
diff --git a/bin/task-lib b/bin/task-lib
--- a/bin/task-lib
+++ b/bin/task-lib
@@ -54,8 +54,8 @@ taskClearFHS() {
   local tmpdir=$(tagValue "tmp")"/$1"
 
   # fixme: test mode
-  dockerExec rm -rf {"$btree","$srcdir","$bindir","$tmpdir"}
-  [[ -d "$btree" ]] && rm -rf "$btree"
+  # dockerExec rm -rf {"$btree","$srcdir","$bindir","$tmpdir"}
+  # [[ -d "$btree" ]] && rm -rf "$btree"
 }
 
 # todo: refactor
@@ -69,16 +69,16 @@ taskInit() {
      [ -d $(guestCreateFHS  "tmp" $task) ]
   then
     # fixme: test mode
-    # info "taskInit /$task/" "... taskClearFHS skipped ..."
-    info $task "dirs ..."
-    taskClearFHS $task
+    info "taskInit /$task/" "... taskClearFHS skipped ..."
+    # info $task "dirs ..."
+    # taskClearFHS $task
   fi
 
   # fixme: test mode
-  # info "taskInit /$task/" "... sources skipped ..."
-  taskMakeFHS $task
-  info $task "sources ..."
-  [[ $(dockerAptSources $task) -eq 0 ]] || error 1 $task "apt-get source failed!"
+  info "taskInit /$task/" "... sources skipped ..."
+  # taskMakeFHS $task
+  # info $task "sources ..."
+  # [[ $(dockerAptSources $task) -eq 0 ]] || error 1 $task "apt-get source failed!"
 }
 
 # get task dcs filename: taskDsc <task>
@@ -456,10 +456,10 @@ taskFinalDepends() {
       p_level="$level"
 
       # todo: find better way to inform
-      echo -ne "\t$COLOR_GRAY" >&2
-      [[ $li -lt 10 ]] && echo -n " " >&2
-      [[ $li -lt 100 ]] && echo -n " " >&2
-      echo -e "$li $chain_dir$COLOR_OFF" >&2
+      # echo -ne "\t$COLOR_GRAY" >&2
+      # [[ $li -lt 10 ]] && echo -n " " >&2
+      # [[ $li -lt 100 ]] && echo -n " " >&2
+      # echo -e "$li $chain_dir$COLOR_OFF" >&2
 
       continue
     fi
@@ -483,10 +483,10 @@ taskFinalDepends() {
       echo "$li $bspec $provides" >> "$pkgs_out"
 
       # todo: find better way to inform
-      echo -ne "\t$COLOR_YELLOW" >&2
-      [[ $li -lt 10 ]] && echo -n " " >&2
-      [[ $li -lt 100 ]] && echo -n " " >&2
-      echo -e "$li $bname$COLOR_OFF" >&2
+      # echo -ne "\t$COLOR_YELLOW" >&2
+      # [[ $li -lt 10 ]] && echo -n " " >&2
+      # [[ $li -lt 100 ]] && echo -n " " >&2
+      # echo -e "$li $bname$COLOR_OFF" >&2
 
       cpkg_bnames+=("$bname")
       cpkg_bspecs+=("$bspec")
@@ -510,10 +510,10 @@ taskFinalDepends() {
         echo "$c_li $c_bspec $c_provides" >> "$pkgs_out"
 
         # todo: find better way to inform
-        echo -ne "\t$COLOR_YELLOW" >&2
-        [[ $c_li -lt 10 ]] && echo -n " " >&2
-        [[ $c_li -lt 100 ]] && echo -n " " >&2
-        echo -e "$c_li $c_bname$COLOR_OFF" >&2
+        # echo -ne "\t$COLOR_YELLOW" >&2
+        # [[ $c_li -lt 10 ]] && echo -n " " >&2
+        # [[ $c_li -lt 100 ]] && echo -n " " >&2
+        # echo -e "$c_li $c_bname$COLOR_OFF" >&2
 
         j=$(( $j + 1 ))
 
@@ -525,10 +525,10 @@ taskFinalDepends() {
         retutn 1
       else
         # todo: find better way to inform
-        echo -ne "\t$COLOR_YELLOW" >&2
-        [[ $c_li -lt 10 ]] && echo -n " " >&2
-        [[ $c_li -lt 100 ]] && echo -n " " >&2
-        echo -e "$(( $i + $j + 1)) $bname$COLOR_OFF" >&2
+        # echo -ne "\t$COLOR_YELLOW" >&2
+        # [[ $c_li -lt 10 ]] && echo -n " " >&2
+        # [[ $c_li -lt 100 ]] && echo -n " " >&2
+        # echo -e "$(( $i + $j + 1)) $bname$COLOR_OFF" >&2
 
         i=$(( $i + $j ))
         p_level="$pp_level"
@@ -554,10 +554,10 @@ taskFinalDepends() {
     echo "$li $bspec $provides" >> "$pkgs_out"
 
     # todo: find better way to inform
-    echo -ne "\t" >&2
-    [[ $li -lt 10 ]] && echo -n " " >&2
-    [[ $li -lt 100 ]] && echo -n " " >&2
-    echo "$li $chain_dir" >&2
+    # echo -ne "\t" >&2
+    # [[ $li -lt 10 ]] && echo -n " " >&2
+    # [[ $li -lt 100 ]] && echo -n " " >&2
+    # echo "$li $chain_dir" >&2
 
   done #? /main
 
